### PR TITLE
Submitting Assignment #2 - Kom el-Hettan - Rachel Streufert Honors Option

### PR DESCRIPTION
**Pull request by Streufertr**
Turning in assignment #2 for Kom el-Hettan (Rachel Streufert honors option).

### CODE REVIEW

**Comment by geyerbri** [comment]
This pull request is going to the correct location. However, you still need to rename your images without uppercase letters or spaces, then adjust the filenames of those images in your code.

**Comment by Streufertr** [comment]
Brian,

Are underscores not allowed?

-Rachel Streufert

**Comment by geyerbri** [comment]
Underscores are perfectly acceptable. 

One of your files has underscores, but also uppercase letters, which are the issue.

**Comment by Streufertr** [comment]
Oh, no.  I forgot to sync my local repo to the online one.  I’m so sorry.

But I’m still having a problem.  I’m lowercasing the name of one of my images, and referencing the lowercased one in my code and it’s working fine.  The problem is that the image file name in GitHub is still uppercase.  And no matter how many times I try to change it in the image file, it doesn’t have an option to commit changes on my desktop app.

-Rachel Streufert

**Comment by Streufertr** [comment]
Never mind.  I'll just change the whole name.  Thanks letting me know what I was doing wrong, and sorry again for the mistake.

**Comment by geyerbri** [comment]
Thank you for making these adjustments! I don't see any other issues at the moment.

Thank you!

**Comment by geyerbri** [comment]
Please email me to setup a way for you to create a second pin on our map, since you will only be able to fill out our form once.

**Pull request merged**
