### PR TITLE
Assignment 1: Kerma 

### PR DESCRIPTION
**Pull request by piatekma**

### CODE REVIEW

**Comment by geyerbri** [comment]
Please rename your folder and file to simply "kerma" (so, delete "-site").

Once you've made that change, committed it, synced it, and made sure it is on both of your branches, it will automatically show up here. So you won't need to make a second pull request to send it to me.

When you've made the changes, please comment here to let me know.

**Comment by watrall** [comment]
this assignment won't be considered properly submitted until you've fixed this issue

**Comment by piatekma** [comment]
I did it but it's not saving for some reason, I don't know what I'm doing wrong. What are the LEADR hours so I can go in for some help?

**Comment by watrall** [comment]
What do you mean "its not saving?"  You just have to rename the file and the folder in your local (cloned) copy (on your hard drive).  From there, just open the github desktop application commit the changes, and then sync (which sends your changes to the repository to GitHub (the cloud) and creates a pull request.  

If you are having trouble figuring out how to rename a file folder:

For Mac - http://osxdaily.com/2010/03/18/how-to-rename-a-file-or-folder-in-mac-os-x/

For Windows - http://www.computerhope.com/issues/ch000846.htm

**Comment by watrall** [comment]
again, I would like to remind you that this assignment **will not** be considered completed until you fix this issue.

**Comment by watrall** [comment]
This is _still_ sitting here and hasn't been dealt with.  Again, this is not considered successfully submitted...which means you won't get a grade for it unless you fix this issue.

**Comment by piatekma** [comment]
I've changed it

**Comment by piatekma** [comment]
I've fixed everything that was asked, there's a space I was told you'd help me fix later, and this is my submission for assignment 2.

**Pull request merged**
