### PR TITLE
Pull Request Assignment 1-Buto

### PR DESCRIPTION
**Pull request by dripandtick**

### CODE REVIEW

**Comment by geyerbri** [comment]
Please remove "-site" from both your folder and file name. 

Additionally, ".html" is twice in your file name, probably because your computer hides file extensions and so it looked to you like you needed to type ".html" to get it to show up. So please delete ".html" from your file name so that it isn't repeated.

Once you've made those changes, please commit them, sync, then make sure the changes appear on both your branches. Once you've done all that, the change will automatically be added to this pull request, so you won't need to make another one to send them to me.

After you've done all this, please comment here so I know you have done them and I can accept your work.

**Comment by watrall** [comment]
this assignment won't be considered properly submitted until you've fixed this issue

**Comment by dripandtick** [comment]
Okay I committed the changes, but I'm only seeing them on gh pages and not
the master yet.

**Comment by dripandtick** [comment]
Actually, I think I'm all set now.

**Comment by geyerbri** [comment]
Thank you for deleting the extra things in your names, but you've now introduced uppercase letters in both your folder and file name.

You'll now need to change them to all lowercase. The thing is, it isn't as easy as just changing them, committing, and syncing. First, change them to all lowercase. Second, move your site's folder ("buto") to your desktop and commit the change in your application (the commit will appear as a deletion). Third, sync this change to the internet. Fourth, back on your own computer, move your folder back into the sites folder. Fifth, commit again (the commit will appear as an addition, with the correct, all lowercase file and folder names). Sixth, sync again to the internet. This will cause the updated all lowercase names to appear here.

**Comment by dripandtick** [comment]
Okay changes made.

**Comment by geyerbri** [comment]
Thank you

**Pull request merged**
