### PR TITLE
Potter DAEA assignment #2

### PR DESCRIPTION
**Pull request by potter44**

### CODE REVIEW

**Comment by potter44** [comment]
assignment #2

**Comment by geyerbri** [comment]
Be advised, in your html file, lines 73 and 90 are extra and will most likely break your webpage if you do not delete them.

**Comment by geyerbri** [comment]
I think my last comment was not clear enough, so I apologize.

On lines 73 and 90 there are extra `<figure>`  tags that will most likely break your webpage. Before, these were on lines of their own, but now they are tacked on to the beginning of the code that follows them. Please delete these extra tags. If you do not understand what I mean, please feel free to ask for clarification.

**Comment by watrall** [comment]
you need to fix this before I accept it.  If you don't fix the issues, you won't get credit for the assignment

**Comment by potter44** [comment]
I think I fixed it

**Comment by potter44** [comment]
I deleted the extra <figure>

**Comment by geyerbri** [comment]
You have indeed deleted the extra tags.

Thank you.

**Pull request merged**
