### PR TITLE
Final submission Madison Piatek

### PR DESCRIPTION
**Pull request by piatekma**
Submitted the project on time but did the pull request wrong. Emailed Brian about fixing it, this is the correct pull request submission.

### CODE REVIEW

**Comment by geyerbri** [comment]
Thank you for creating this one.

Be advised however that this pull request comes from your own master branch, rather than your own gh-pages branch. It appears you have not been backing up your work from your own gh-pages branch -where I can see you've been doing all your work - so your work doesn't exist on both.

To resolve this, you can either do a pull request to your own master branch from your own gh-pages branch, which will get your work to show up here automatically, or you can create a new pull request that goes to msu-anthropology's master branch from your own gh-pages branch.

**Comment by piatekma** [comment]
Did it.

**Comment by geyerbri** [comment]
I made a comment on your [local pull request](https://github.com/piatekma/daea-fs16/pull/9). Please address the issues I discuss there.

**Comment by piatekma** [comment]
Hello Brian,


There have been a lot of problems with me receiving things through email/d2l while off campus. I had a few meetings with you as well as with other LEADR members and the last meeting I had with you I was told that my submission was completed successfully so I am a bit confused with what is wrong. If you could email me back ASAP I'm a bit concerned with my grade for this project if it wasn't received properly.


Madison Piatek

________________________________

**Pull request closed without merging**
