### PR TITLE
Submitting Assignment #2 - Kom el-Hettan - Rachel Streufert

### PR DESCRIPTION
**Pull request by Streufertr**
Turning in assignment #2 with Kom el-Hettan (Rachel Streufert Honors Option).

### CODE REVIEW

**Comment by geyerbri** [comment]
Please be advised, there are a few issues with your current work. 

First, all of your images contain uppercase letters and/or spaces. Second, in your code, you have incorrectly written the `src` part of your `img` code. You have written "/Users/rachel/Documents/daea-fs16/sites/kom-el-hettan/images/Sekhmet.jpg", where your code should only include "images/" and then the corrected names of your files (after you've fixed the issue mentioned above).

Finally, this pull request is sending your work to the gh-pages branch of the msu-anthropology repo. Please create a new pull request that sends your work to the master branch instead. Consult the last article on the wiki to see what settings are needed for turning in your work.

**Comment by Streufertr** [comment]
Brian,

I tried just doing “images/“, but the images didn’t show up.  Is that what’s supposed to happen?  The only way I could get it to work was with the long source code.  

I wasn’t there on Tuesday, so I was just trying to figure it out today. 

Thanks,

Rachel Streufert

**Comment by Streufertr** [comment]
Brian,

Actually, now it’s working.  I don’t know why it wasn’t before…Sorry for the confusion.

Thanks,

Rachel Streufert

**Comment by geyerbri** [comment]
I see your other pull request now, so I will close this one. Please see my comment there.

**Pull request closed without merging**
